YAHOO.namespace("ballhype");
YAHOO.ballhype.autoComplete=function(){return{init:function(){function a(b,c){var d=new YAHOO.widget.DS_XHR(YAHOO.ballhype.siUr+"autocomplete/",["AutoCompletes","DisplayName","Url","DisplayType","Id"]);d.scriptQueryParam="prefix";d.queryMatchContains=true;d.responseType=YAHOO.widget.DS_XHR.TYPE_JSON;b=new YAHOO.widget.AutoComplete(b,c,d);b.minQueryLength=2;b.allowBrowserAutocomplete=false;b.maxResultsDisplayed=10;b.useShadow=true;b.useIFrame=true;b.highlightClassName="autoCompleteHighlight";function e(f,
g){f=g[2];document.location=f[1]}b.itemSelectEvent.subscribe(e);b.formatResult=function(f,g){var h=f[0],i=h.substr(0,g.length);g=h.substr(g.length);f=f[2];i=['<span class="highlight">',i,"</span>",g,'<br/><span class="meta">',f,"</span>"];return i.join("")};b.doBeforeExpandContainer=function(f,g){var h=YAHOO.util.Dom.getXY(f);h[1]+=YAHOO.util.Dom.get(f).offsetHeight;YAHOO.util.Dom.setXY(g,h);return true}}document.getElementById("tagFindInput")&&a("tagFindInput","tagFindContainer");document.getElementById("tagFindInputSearch")&&
a("tagFindInputSearch","tagFindContainerSearch")},validateForm:function(){return false}}}();function setupButton(){var a=YAHOO.util.Dom.getElementsByClassName("jsButton","span"),b;for(b=0;b<a.length;b++)try{new YAHOO.widget.Button(a[b])}catch(c){}a=YAHOO.util.Dom.getElementsByClassName("fsButton","input");for(b=0;b<a.length;b++)try{new YAHOO.widget.Button(a[b])}catch(d){}}YAHOO.util.Event.addListener(window,"load",YAHOO.ballhype.autoComplete.init);YAHOO.util.Event.onDOMReady(setupButton);
function castCommentVote(a,b){if(YAHOO.ballhype.uli){var c=document.getElementById(a);c={success:function(d){if(d.responseText=="hater"){d=d.argument[0].id.split(".")[1];showCommentHaterOverlay(d)}else d.argument[0].innerHTML=d.responseText},argument:[c]};a=YAHOO.util.Connect.asyncRequest("GET",b+a+"/",c,null)}else{a=a.split(".")[1];showLoginOverlay(a,"cvt.","voting")}}function confirmDelete(a,b){if(confirm("Are you sure you would like to delete "+a+"?"))window.location=b}
function debug(a){var b="";for(var c in a)b+=c+": "+a[c]+"\t";alert(b)}
function handlePickResponse(a,b){b=b.PickResults;var c=document.getElementById("roadpick."+a);c.className=b.userRoad?"selectedPick":"nonPick";c=document.getElementById("homepick."+a);c.className=b.userHome?"selectedPick":"nonPick";if(c=document.getElementById("roadpicks."+a)){var d='<a href="javascript:showGamePicks('+a+", 'road', 'Road');\">"+b.roadCount+" pick";if(b.roadCount!==1)d+="s";d+="</a>";if(b.userRoad)d+=' <a href="javascript:pickGame('+a+", '"+YAHOO.ballhype.siUr+"game."+a+"/clear/road/');\">[clear your pick]</a>";
c.innerHTML=d}if(c=document.getElementById("homepicks."+a)){d='<a href="javascript:showGamePicks('+a+", 'home', 'Home');\">"+b.homeCount+" pick";if(b.homeCount!==1)d+="s";d+="</a>";if(b.userHome)d+=' <a href="javascript:pickGame('+a+", '"+YAHOO.ballhype.siUr+"game."+a+"/clear/home/');\">[clear your pick]</a>";c.innerHTML=d}}
function addWatch(a,b){if(YAHOO.ballhype.uli){b={success:function(c){elem=document.getElementById("watch."+c.argument[0]);var d="I'm watching";if(c.argument[1])d="I watched";elem.innerHTML='<img src="/media/img/icon/television.png" width="16" height="16" class="siteicon" alt="'+d+' this game"/> '+d+' <a href="javascript:removeWatch('+c.argument[0]+", "+c.argument[1]+');" class="watch-action">[clear]</a>'},argument:[a,b]};a=YAHOO.util.Connect.asyncRequest("GET",YAHOO.ballhype.siUr+"game."+a+"/add_user/",
b,null)}else showLoginOverlay(a,"gm.","marking games as watched")}
function removeWatch(a,b){if(YAHOO.ballhype.uli){b={success:function(c){elem=document.getElementById("watch."+c.argument[0]);var d="watching";if(c.argument[1])d="watched";elem.innerHTML='<a href="javascript:addWatch('+c.argument[0]+", "+c.argument[1]+');" class="watch-action">[mark '+d+"]</a>"},argument:[a,b]};a=YAHOO.util.Connect.asyncRequest("GET",YAHOO.ballhype.siUr+"game."+a+"/remove_user/",b,null)}else showLoginOverlay(a,"gm.","marking games as watched")}
function pickGame(a,b){if(YAHOO.ballhype.uli){a={success:function(c){var d=eval("("+c.responseText+")");handlePickResponse(c.argument[0],d)},argument:[a]};b=YAHOO.util.Connect.asyncRequest("GET",b,a,null)}else showLoginOverlay(a,"gm.","picking games")}function pickGameGroup(a,b,c){if(YAHOO.ballhype.uli){a={success:function(d){handleGroupPickResponse(d.argument[0],c)},argument:[a]};b=YAHOO.util.Connect.asyncRequest("GET",b,a,null)}else showLoginOverlay(a,"gm.","picking games")}
function handleGroupPickResponse(a,b){a=b?document.getElementById("roadpick."+a):document.getElementById("homepick."+a);b=YAHOO.util.Dom.getElementsByClassName("selectedPick","div");for(var c=0;c<b.length;c++){YAHOO.util.Dom.removeClass(b[c],"selectedPick");YAHOO.util.Dom.addClass(b[c],"nonPick")}YAHOO.util.Dom.removeClass(a,"nonPick");YAHOO.util.Dom.addClass(a,"selectedPick")}
function pickOption(a){var b={success:function(c){elem=document.getElementById("poll_options");elem.innerHTML=c.responseText},argument:[a]};a=YAHOO.util.Connect.asyncRequest("GET",YAHOO.ballhype.siUr+"post/poll/option."+a+"/",b,null)}function padZeroes(a){return a<10?"0"+a:a.toString()}
function loadContent(a,b){var c=document.getElementById(a),d={success:function(e){e.argument[0].innerHTML=e.responseText;setupButton()},failure:function(e){},argument:[c]};b=YAHOO.util.Connect.asyncRequest("GET",b,d,null);c.innerHTML='<div class="center"><img src="/media/img/loading.gif" width="32" height="32" alt="Loading" class="loading"></div>';anchorScroll(a,true)}function activateBox(a){a.value="";YAHOO.util.Dom.setStyle(a,"color","#000");YAHOO.util.Dom.setStyle(a,"fontWeight","bold")}
function showHide(a,b){a=document.getElementById(a);b?YAHOO.util.Dom.removeClass(a,"hidden"):YAHOO.util.Dom.addClass(a,"hidden")}function showHideTracker(a,b){a=document.getElementById(a);if(b){YAHOO.util.Dom.setStyle(a,"opacity",0);YAHOO.util.Dom.removeClass(a,"hidden");b=new YAHOO.util.Anim(a,{opacity:{to:1}},0.6,YAHOO.util.Easing.easeOut);b.onComplete.subscribe(updateTrackerLast);b.animate()}else YAHOO.util.Dom.addClass(a,"hidden")}
function mostWidgetToggle(a,b){if(b)autoTrackerAdvanced=false;showHideTracker("mdtrack",a=="mdtrack");showHideTracker("mvtrack",a=="mvtrack");showHideTracker("mhtrack",a=="mhtrack");showHideTracker("mwtrack",a=="mwtrack");YAHOO.util.Dom.addClass(a+"_link","most-widget-link-selected");a!="mdtrack"&&YAHOO.util.Dom.removeClass("mdtrack_link","most-widget-link-selected");a!="mvtrack"&&YAHOO.util.Dom.removeClass("mvtrack_link","most-widget-link-selected");a!="mhtrack"&&YAHOO.util.Dom.removeClass("mhtrack_link",
"most-widget-link-selected");a!="mwtrack"&&YAHOO.util.Dom.removeClass("mwtrack_link","most-widget-link-selected")}function pauseTracker(){autoTrackerPaused=true}function unpauseTracker(){autoTrackerPaused=false}function updateTracker(){if(autoTrackerAdvanced)if(autoTrackerPaused)updateTrackerLast();else{var a=new YAHOO.util.Anim(trackerPanes[currentTrackerPane],{opacity:{to:0}},0.6,YAHOO.util.Easing.easeOut);a.onComplete.subscribe(updateTrackerNext);a.animate()}}
function updateTrackerNext(){if(autoTrackerAdvanced){var a=0;if(currentTrackerPane+1<trackerPanes.length)a=currentTrackerPane+1;mostWidgetToggle(trackerPanes[a],false);currentTrackerPane=a}}function updateTrackerLast(){if(autoTrackerAdvanced)var a=setTimeout("updateTracker()",7000)}function trackEvent(a,b,c,d){_gaq.push(["_trackEvent",a,b,c,d])}
function handleVoteResponseUpOrDown(a,b,c){var d=b.VoteResults;a=c=="up"?a:document.getElementById(a.id.replace(c,"up"));c=document.getElementById(a.id.replace("up","down_no"));var e=document.getElementById(a.id.replace("up","down_yes"));YAHOO.util.Dom.getElementsByClassName("points_count","span",a)[0].innerHTML=d.yesCount-d.noCount;if(d.userYes){YAHOO.util.Dom.setStyle(c,"display","none");YAHOO.util.Dom.setStyle(e,"display","inline");YAHOO.util.Dom.addClass(a,"selected");facebookConnectedUser()&&
b.ShareVotes&&showFacebookVoteFeed(b)}else{c.innerHTML=d.userNo?"undo vote down":"vote down";YAHOO.util.Dom.setStyle(e,"display","none");YAHOO.util.Dom.setStyle(c,"display","inline");YAHOO.util.Dom.removeClass(a,"selected")}trackEvent("Vote",String(d.userYes))}
function castVoteUpOrDown(a,b,c){if(YAHOO.ballhype.uli){a={success:function(d){var e=eval("("+d.responseText+")");if(e.VoteHater)showHaterOverlay(d.argument[0].id.split(".")[1]);else if(e.SameAddress)showSameAddressOverlay(d.argument[0].id.split(".")[1]);else e.TooFast?showTooFastOverlay(d.argument[0].id.split(".")[1]):handleVoteResponseUpOrDown(d.argument[0],e,c)},failure:function(d){},argument:[a]};b=YAHOO.util.Connect.asyncRequest("GET",b,a,null)}else{b=a.id.split(".")[1];showLoginOverlay(b,"stry.",
"voting")}}
function setupHoverDirection(a,b,c,d){a=YAHOO.util.Dom.getElementsByClassName(a,"div");for(var e=[],f=[],g=0;g<a.length;g++){var h=a[g].id;if(h.indexOf("up")>-1)a[g].counterpart=document.getElementById(h.replace("up","down"));else if(h.indexOf("down")>-1)a[g].counterpart=document.getElementById(h.replace("down","up"));YAHOO.util.Event.addListener(a[g],"mouseover",b,a[g]);YAHOO.util.Event.addListener(a[g],"mouseout",c,a[g]);if(d&&a[g].id)if(YAHOO.util.Dom.hasClass(a[g],"vote-selected"))f[f.length]=a[g];
else e[e.length]=a[g]}if(d){new YAHOO.widget.Tooltip(d.replace(" ","_")+"_tt",{zIndex:1,context:e,text:d});new YAHOO.widget.Tooltip(d.replace(" ","_")+"undo_vote_tt",{zIndex:1,context:f,text:"undo vote"})}}function mouseOverValid(a,b){return!YAHOO.util.Dom.hasClass(b,"widget-vote-hover")}
function voteMouseOver(a,b,c,d){if(mouseOverValid(a,b)){(new YAHOO.util.ColorAnim(b,{backgroundColor:d},0.3,null)).animate();YAHOO.util.Dom.addClass(b,"widget-vote-hover");YAHOO.util.Dom.getElementsByClassName("vote-arrow","img",b)[0].src=c;return true}return false}
function voteMouseOverUp(a,b){var c=getVotingPath()+"up.gif",d={to:getVoteSelectedColor(),from:getVoteColor()};if(YAHOO.util.Dom.hasClass(b,"vote-selected")){c=getVotingPath()+"up_light.gif";d={to:getVoteColor(),from:getVoteSelectedColor()}}if((a=voteMouseOver(a,b,c,d))&&b.counterpart&&YAHOO.util.Dom.hasClass(b.counterpart,"vote-selected")){YAHOO.util.Dom.setStyle(b.counterpart,"backgroundColor",getVoteColor());YAHOO.util.Dom.getElementsByClassName("vote-arrow","img",b.counterpart)[0].src=getVotingPath()+
"down_light.gif"}}
function voteMouseOverDown(a,b){var c=getVotingPath()+"down.gif",d={to:getVoteSelectedColor(),from:getVoteColor()};if(YAHOO.util.Dom.hasClass(b,"vote-selected")){c=getVotingPath()+"down_light.gif";d={to:getVoteColor(),from:getVoteSelectedColor()}}if((a=voteMouseOver(a,b,c,d))&&b.counterpart&&YAHOO.util.Dom.hasClass(b.counterpart,"vote-selected")){YAHOO.util.Dom.setStyle(b.counterpart,"backgroundColor",getVoteColor());YAHOO.util.Dom.getElementsByClassName("vote-arrow","img",b.counterpart)[0].src=getVotingPath()+
"up_light.gif"}}function mouseOutValid(a,b){a=YAHOO.util.Event.getRelatedTarget(a);return!a||!a.parentNode||!a.parentNode.id||a.parentNode.id!==b.id}function checkColor(){var a=this.getEl();YAHOO.util.Dom.hasClass(a,"widget-vote-hover")||YAHOO.util.Dom.hasClass(a,"vote-selected")&&(!a.counterpart||!YAHOO.util.Dom.hasClass(a.counterpart,"widget-vote-hover"))?YAHOO.util.Dom.setStyle(a,"backgroundColor",getVoteSelectedColor()):YAHOO.util.Dom.setStyle(a,"backgroundColor",getVoteColor())}
function voteMouseOut(a,b,c,d){if(mouseOutValid(a,b)){a=new YAHOO.util.ColorAnim(b,{backgroundColor:d},0.3,null);a.onComplete.subscribe(checkColor);a.animate();YAHOO.util.Dom.removeClass(b,"widget-vote-hover");YAHOO.util.Dom.getElementsByClassName("vote-arrow","img",b)[0].src=c;return true}return false}
function voteMouseOutUp(a,b){var c=getVotingPath()+"up_light.gif",d={to:getVoteColor(),from:getVoteSelectedColor()};if(YAHOO.util.Dom.hasClass(b,"vote-selected")){c=getVotingPath()+"up.gif";d={to:getVoteSelectedColor(),from:getVoteColor()}}if((a=voteMouseOut(a,b,c,d))&&b.counterpart&&YAHOO.util.Dom.hasClass(b.counterpart,"vote-selected")){YAHOO.util.Dom.setStyle(b.counterpart,"backgroundColor",getVoteSelectedColor());YAHOO.util.Dom.getElementsByClassName("vote-arrow","img",b.counterpart)[0].src=getVotingPath()+
"down.gif"}}
function voteMouseOutDown(a,b){var c=getVotingPath()+"down_light.gif",d={to:getVoteColor(),from:getVoteSelectedColor()};if(YAHOO.util.Dom.hasClass(b,"vote-selected")){c=getVotingPath()+"down.gif";d={to:getVoteSelectedColor(),from:getVoteColor()}}if((a=voteMouseOut(a,b,c,d))&&b.counterpart&&YAHOO.util.Dom.hasClass(b.counterpart,"vote-selected")){YAHOO.util.Dom.setStyle(b.counterpart,"backgroundColor",getVoteSelectedColor());YAHOO.util.Dom.getElementsByClassName("vote-arrow","img",b.counterpart)[0].src=getVotingPath()+
"up.gif"}}function metaMouseOver(a,b){YAHOO.util.Dom.addClass(b,"widget-meta-hover")}function metaMouseOut(a,b){YAHOO.util.Dom.removeClass(b,"widget-meta-hover")}function setupHovers(){setupHoverDirection("widget-vote-up",voteMouseOverUp,voteMouseOutUp,getVoteTip());setupHoverDirection("widget-vote-down",voteMouseOverDown,voteMouseOutDown,"vote it down");setupHoverDirection("widget-meta",metaMouseOver,metaMouseOut,null)}YAHOO.util.Event.addListener(window,"load",setupHovers);
YAHOO.ballhype.stepIncrement=20;YAHOO.ballhype.killTimeout=null;YAHOO.ballhype.running=false;YAHOO.ballhype.nextStep=null;function killScroll(){window.clearTimeout(YAHOO.ballhype.killTimeout);YAHOO.ballhype.running=false;YAHOO.ballhype.stepIncrement=50}function callNext(a,b,c){return function(){scrollStep(a,b,c)}}
function scrollStep(a,b,c){if(!YAHOO.ballhype.running||c&&a>=b||!c&&a<=b)killScroll();else{if(c&&a>=b-2*YAHOO.ballhype.stepIncrement||!c&&a<=b-2*YAHOO.ballhype.stepIncrement)YAHOO.ballhype.stepIncrement*=0.55;window.scrollTo(0,a);YAHOO.ballhype.nextStep=callNext(+a+YAHOO.ballhype.stepIncrement,b,c);window.setTimeout(YAHOO.ballhype.nextStep,10)}}
function anchorScroll(a,b){if(a=YAHOO.util.Dom.get(a)){YAHOO.ballhype.running=true;a=YAHOO.util.Dom.getY(a)-6<0?0:YAHOO.util.Dom.getY(a)-6;var c=document.all?document.documentElement.scrollTop:window.pageYOffset,d=true;if(c>a){YAHOO.ballhype.stepIncrement*=-1;d=false}else if(b)return;YAHOO.ballhype.killTimeout=window.setTimeout(killScroll,6000);scrollStep(c+YAHOO.ballhype.stepIncrement,a,d)}}YAHOO.ballhype.loginOverlays={};
function closeMessageOverlay(a){YAHOO.ballhype.loginOverlays[a]&&YAHOO.ballhype.loginOverlays[a].hide()}function getRelativePath(){var a=document.location.toString(),b=a.indexOf("/",9);return a.substring(b)}function flagInappropriateComment(a,b){flagItem(a,YAHOO.ballhype.siUr+"comment."+b+"."+a+"/flag/inappropriate_comment/")}function flagPhoto(a,b){flagItem(a,YAHOO.ballhype.siUr+"photo."+a+"/flag/"+b+"/")}function flagStory(a,b){flagItem(a,YAHOO.ballhype.siUr+"story."+a+"/flag/"+b+"/")}
function flagIncorrectTag(a){flagItem(a,YAHOO.ballhype.siUr+"story."+a+"/flag/incorrect_tag/")}function flagInappropriateBookmark(a){flagItem(a,YAHOO.ballhype.siUr+"bookmark."+a+"/flag/inappropriate_bookmark/")}function flagIncorrectBookmarkTag(a){flagItem(a,YAHOO.ballhype.siUr+"bookmark."+a+"/flag/incorrect_classification/")}function flagItem(a,b){b=YAHOO.util.Connect.asyncRequest("GET",b,null,null);closeMessageOverlay(a)}
function showFlagStoryOverlay(a){var b="";b=document.location.pathname.indexOf("/video/")>-1?'<a href="javascript:flagStory('+a+", 'video_unavailable')\">[video unavailable]</a>":'<a href="javascript:flagStory('+a+", 'broken_link')\">[broken link]</a>";b="Flag for "+YAHOO.ballhype.siNa+' staff:<br/><a href="javascript:flagStory('+a+", 'inappropriate_story')\">[inappropriate story]</a><br/><a href=\"javascript:flagStory("+a+", 'incorrect_tag')\">[incorrect tags or title]</a><br/>"+b+'<br/><a href="javascript:closeMessageOverlay('+
a+');">[cancel]</a>';showMessageOverlay(a,"stry.",b)}function showFlagPhotoOverlay(a){var b="Flag for "+YAHOO.ballhype.siNa+' staff:<br/><a href="javascript:flagPhoto('+a+", 'inappropriate_photo')\">[inappropriate photo]</a><br/><a href=\"javascript:flagPhoto("+a+", 'incorrect_tag')\">[incorrect tag]</a><br/><a href=\"javascript:flagPhoto("+a+", 'duplicate')\">[duplicate]</a><br/><a href=\"javascript:closeMessageOverlay("+a+');">[cancel]</a>';showMessageOverlay(a,"prevphoto.",b)}
function showFlagBookmarkOverlay(a){var b="Flag for "+YAHOO.ballhype.siNa+' staff:<br/><a href="javascript:flagInappropriateBookmark('+a+')">[inappropriate site]</a><br/><a href="javascript:flagIncorrectBookmarkTag('+a+')">[incorrect classification]</a><br/><a href="javascript:closeMessageOverlay('+a+');">[cancel]</a>';showMessageOverlay(a,"bookmark.",b)}
function showFlagCommentOverlay(a,b){b="Flag for "+YAHOO.ballhype.siNa+' staff:<br/><a href="javascript:flagInappropriateComment('+a+", '"+b+'\')">[inappropriate comment]</a><br/><a href="javascript:closeMessageOverlay('+a+');">[cancel]</a>';showMessageOverlay(a,"stry.",b)}
function showHaterOverlay(a){var b="Hey there, don't be a hater.<br/>You need to hype up more stories<br/>before you can vote this story down.<br/><a href=\"javascript:closeMessageOverlay("+a+');">[close]</a>';showMessageOverlay(a,"stry.",b)}function showCommentHaterOverlay(a){var b="Hey there, don't be a hater.<br/>You need to hype up more comments<br/>before you can vote this comment down.<br/><a href=\"javascript:closeMessageOverlay("+a+');">[close]</a>';showMessageOverlay(a,"cvt.",b)}
function showSameAddressOverlay(a){var b="Hey there, we're getting too many votes<br/>from your address for this story.<br/><a href=\""+YAHOO.ballhype.siUr+'contact/">Contact us</a> if you think this is incorrect.<br/><a href="javascript:closeMessageOverlay('+a+');">[close]</a>';showMessageOverlay(a,"stry.",b)}function showTooFastOverlay(a){var b='Whoa--can you really read that fast?<br/><a href="javascript:closeMessageOverlay('+a+');">[close]</a>';showMessageOverlay(a,"stry.",b)}
function showLoginOverlay(a,b,c,d){if(d==null)d=getRelativePath();c="";if(YAHOO.ballhype.fbCo)c="<p>or sign in with</p><p class=\"fbc-button\"><a href=\"#\" onclick=\"loadingOverlay('facebookOverlay', '', 'Connect with Facebook');closeMessageOverlay("+a+");FB.Connect.requireSession(function() { facebookLogin('"+d+'\'); }); return false;"><img id="fb_login_image" class="fb-button" src="http://static.ak.fbcdn.net/images/fbconnect/login-buttons/connect_light_medium_short.gif" alt="Connect" /></a></p>';
d='<div id="formOverlay"><p class="heading">You\'ve got to log in to do that.</p><form method="post" action="'+YAHOO.ballhype.siUr+'login/" id="loginForm" class="join-login"><input type="hidden" name="next" value="'+d+'" /><table><tr><td class="input-title"><label for="id_username">Username</label></td><td><input type="text" id="id_username" class="vTextField required" name="username" value="" maxlength="30"/></td><td rowspan="2" class="action-col">'+c+'</td></tr><tr><td class="input-title"><label for="id_password">Password</label></td><td><input type="password" id="id_password" class="vPasswordField required" name="password" value="" maxlength="30"/></td></tr><tr><td></td><td colspan="2" class="action-row"><input id="login-button" type="submit" value="Log In" class="fsButton"/><span class="hi-lite"><a href="'+
YAHOO.ballhype.siUr+"accounts/create/?next="+d+'">Create an Account</a></span></td></tr></table></form><p class="right-link"><a href="#" onclick="closeMessageOverlay('+a+'); return false;">Cancel</a></p></div>';showMessageOverlay(a,b,d);login_button=new YAHOO.widget.Button("login-button")}
function showMessageOverlay(a,b,c){if(YAHOO.ballhype.loginOverlays[a])b=YAHOO.ballhype.loginOverlays[a];else{var d=document.getElementById("overlay."+a);b=new YAHOO.widget.Panel(d,{context:[b+a,"tl","tl"],x:0,underlay:"shadow",visible:false,draggable:false,close:false,effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}})}d=getRelativePath();b.setBody(c);c=new YAHOO.util.KeyListener(document,{keys:27},{fn:b.hide,scope:b,correctScope:true});b.cfg.queueProperty("keylisteners",c);b.render();
b.show();YAHOO.ballhype.loginOverlays[a]=b}function historyInit(){try{YAHOO.util.History.initialize("yui-history-field","yui-history-iframe")}catch(a){initTabView()}}function initTabView(){YAHOO.ballhype.tabView=new YAHOO.widget.TabView("tab_set");YAHOO.ballhype.tabView.addListener("activeTabChange",handleTabViewActiveTabChange)}
function tabsetInit(){YAHOO.ballhype.bookmarkedTabViewState=YAHOO.util.History.getBookmarkedState("tab");YAHOO.ballhype.initialTabViewState=YAHOO.ballhype.bookmarkedTabViewState||"0.0";YAHOO.util.History.register("tab",YAHOO.ballhype.initialTabViewState,handleState);YAHOO.util.History.onReady(function(){initTabView();var a=YAHOO.util.History.getCurrentState("tab");handleState(a)});YAHOO.util.Event.addListener(window,"load",historyInit)}
function getTabState(a){return a?parseInt(a.split(".")[0],10):0}function getPageState(a){return a?parseInt(a.split(".")[1],10)||0:0}function addPageQueryString(a,b){if(b>0)a+=a.indexOf("?")>-1?"&p="+b:"?p="+b;return a}
function changePage(a){var b=parseInt(YAHOO.util.History.getCurrentState("tab"),10),c=tabInfo[b];b=c.elemId;var d=document.getElementById(b);if(c=c.dataSrc){c=addPageQueryString(c,a);a={success:function(e){e.argument[0].innerHTML=e.responseText;setupHovers();setupButton()},failure:function(e){},argument:[d]};a=YAHOO.util.Connect.asyncRequest("GET",c,a,null);d.innerHTML='<div class="center"><img src="/media/img/loading.gif" width="32" height="32" alt="Loading" class="loading"></div>';anchorScroll(b,
true)}}function handleState(a){var b=a===YAHOO.ballhype.initialTabViewState;if(b)YAHOO.ballhype.initialTabViewState="-1.-1";var c=getTabState(a);YAHOO.ballhype.tabView.get("activeIndex")!==c&&YAHOO.ballhype.tabView.set("activeIndex",c);a=getPageState(a);if(a>0||c>0||!b)changePage(a)}function handleTabViewActiveTabChange(a){var b=getTabState(YAHOO.util.History.getCurrentState("tab"));a=this.getTabIndex(a.newValue);a!==b&&YAHOO.util.History.navigate("tab",a.toString()+".0")}
function loadPage(a){var b=YAHOO.util.History.getCurrentState("tab");if(a!==getPageState(b)){a=getTabState(b)+"."+a.toString();YAHOO.util.History.navigate("tab",a)}}
function addTab(a,b,c,d){var e=YAHOO.util.History.getBookmarkedState("tab");c=getTabState(e);e=getPageState(e);a=tabInfo[a].dataSrc;if(c===1&&e>0)a=addPageQueryString(a,e);b=new YAHOO.widget.Tab({label:b,dataSrc:a,cacheData:a});if(d)b.loadHandler={success:function(f){this.set("content",f.responseText);setupHovers()},failure:function(f){}};YAHOO.ballhype.tabView.addTab(b)}YAHOO.ballhype.comments={};YAHOO.ballhype.commentPreviews={};
function getTinyMCEEntityEncoding(){return isKHTML()?"raw":"named"}YAHOO.ballhype.CLEANUP_EXPRESSIONS=[[new RegExp(String.fromCharCode(160),"g")," "],[new RegExp("%u2018","g"),"'"],[new RegExp("%u2019","g"),"'"],[new RegExp("%u201C","g"),'"'],[new RegExp("%u201D","g"),'"']];function mceCleanup(a,b){if(a=="get_from_editor")for(a=0;a<YAHOO.ballhype.CLEANUP_EXPRESSIONS.length;a++){var c=YAHOO.ballhype.CLEANUP_EXPRESSIONS[a][0],d=YAHOO.ballhype.CLEANUP_EXPRESSIONS[a][1];b=b.replace(c,d)}return b}
function commentsInit(){tinyMCE.init({cleanup_callback:"mceCleanup",entity_encoding:getTinyMCEEntityEncoding(),convert_urls:false,mode:"none",theme:"advanced",content_css:"/media/css/mce.css",theme_advanced_buttons1:"bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright, justifyfull,bullist,numlist,undo,redo,link,unlink,outdent,indent",theme_advanced_buttons2:"",theme_advanced_buttons3:"",theme_advanced_toolbar_location:"top",theme_advanced_toolbar_align:"left",theme_advanced_path:"false",
accessibility_focus:false,plugins:"tabjump,shortcuts",tabjump_to:"preview_button",extended_valid_elements:"a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style],blockquote[dir|style]"})}
function submitCommentForm(a){var b=document.getElementById("submit_"+a),c=b.parentNode;c={success:function(e){e.argument[0].innerHTML=e.responseText;facebookConnectedUser()&&showFacebookCommentFeed(e.argument[1].action+"info/")},failure:function(e){},argument:[c,b]};var d="comment="+prepareAjaxPost(escape(tinyMCE.getContent()));tinyMCE.execCommand("mceRemoveControl",false,"comment_textarea_"+a);if(a>0)d+="&parent="+a;a=YAHOO.util.Connect.asyncRequest("POST",b.action,c,d)}
function prepareAjaxPost(a){return a.replace(/\+/g,"%2b")}
function showCommentForm(a,b,c,d){if(YAHOO.ballhype.uli){if(!YAHOO.ballhype.comments[b]){var e=document.getElementById("submit_comment."+b);e.innerHTML="";if(b!=-1){var f=document.getElementById("submit_comment.-1");if(YAHOO.util.Dom.getElementsByClassName("jsButton","span",f).length>0)f.innerHTML=""}YAHOO.ballhype.comments[b]=new YAHOO.widget.Module(e,{effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}});e='<ul class="comment_list"><li>\n';e+='<form action="'+a+'" method="POST" id="submit_'+
b+'"';YAHOO.ballhype.uli||(e+=' onsubmit="tinyMCE.triggerSave();"');e+=">\n";if(b>0)e+='<input type="hidden" name="parent" value="'+b+'">\n';e+='<div id="comment_preview.'+b+'"></div>\n';e+='<textarea name="comment" rows="10" id="comment_textarea_'+b+'"></textarea>\n';e+="<br/>\n";e+='<span id="previewButton.'+b+'" class="jsButton nopadButton"><span class="first-child"><a href="javascript:showCommentPreview('+b+", '"+c+'\')" id="preview_button">Preview</a></span></span>\n';e+='<span id="submitButton.'+
b+'" class="jsButton nopadButton"><span class="first-child"><a href="javascript:submitCommentForm('+b+');">'+d+"</a></span></span>\n";e+="</form></li></ul>";YAHOO.ballhype.comments[b].setHeader("");YAHOO.ballhype.comments[b].setBody(e);YAHOO.ballhype.comments[b].render();setupButton();tinyMCE.idCounter=0;tinyMCE.addMCEControl(document.getElementById("comment_textarea_"+b),"comment_textarea_"+b)}}else{a=getRelativePath();showLoginOverlay(b,"submit_comment.","commenting",a)}}
function showCommentPreview(a,b){YAHOO.ballhype.commentPreviews[a]||(YAHOO.ballhype.commentPreviews[a]=new YAHOO.widget.Module("comment_preview."+a,{effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}}));b='<div class="comment-preview">\n';b+='<div class="comment-body">';b+=tinyMCE.getContent();b+="</div>\n";b+='<div class="comment-meta">Posted 0 seconds ago</div>';b+='<div class="clearer"></div>';b+="</div>\n";YAHOO.ballhype.commentPreviews[a].setBody(b);YAHOO.ballhype.commentPreviews[a].render()}
function showHideComment(a,b){showHide("commentbody."+a,b);controlSpan=document.getElementById("comcontrol."+a);controlSpan.innerHTML=b?'<a href="javascript:showHideComment('+a+', false);">[hide]</a> ':'<a href="javascript:showHideComment('+a+', true);">[show]</a> '}
function regionInit(){YAHOO.ballhype.regionPanel=new YAHOO.widget.Panel("region_panel",{width:"350px",underlay:"shadow",close:true,visible:false,draggable:true,effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}});YAHOO.ballhype.regionPanel.setHeader("Choose a Region");var a=new YAHOO.util.KeyListener(document,{keys:27},{fn:YAHOO.ballhype.regionPanel.hide,scope:YAHOO.ballhype.regionPanel,correctScope:true});YAHOO.ballhype.regionPanel.cfg.queueProperty("keylisteners",a);YAHOO.ballhype.regionPanel.render()}
function showRegionPanel(){var a=YAHOO.ballhype.regionPanel.cfg.getProperty("y");YAHOO.ballhype.regionPanel.moveTo(400,a);YAHOO.ballhype.regionPanel.show()}
function filterInit(){YAHOO.ballhype.filterPanel=new YAHOO.widget.Panel("filter_panel",{width:"550px",underlay:"shadow",close:true,visible:false,draggable:true,effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}});YAHOO.ballhype.filterPanel.setHeader("Filter Bookmarks");var a=new YAHOO.util.KeyListener(document,{keys:27},{fn:YAHOO.ballhype.filterPanel.hide,scope:YAHOO.ballhype.filterPanel,correctScope:true});YAHOO.ballhype.filterPanel.cfg.queueProperty("keylisteners",a);YAHOO.ballhype.filterPanel.render()}
function showFilterPanel(){var a=YAHOO.ballhype.filterPanel.cfg.getProperty("y");YAHOO.ballhype.filterPanel.moveTo(200,a);YAHOO.ballhype.filterPanel.show()}function trackClick(a,b){var c=new Image(1,1);c.src=YAHOO.ballhype.siUr+"url_track/"+a+"/"+b+"/?ts="+(new Date).getTime();_gaq.push(["_setDomainName",document.location.host]);_gaq.push(["_trackPageview",YAHOO.ballhype.siUr+"external_click/?type="+b])}function nullVoid(){}
function pause(a){var b=new Date;for(a=b.getTime()+a;b.getTime()<a;)b=new Date}function showRelatedPostMedia(a,b,c){if(YAHOO.ballhype.mediaAds)YAHOO.ballhype.mediaAds++;else YAHOO.ballhype.mediaAds=1;var d=YAHOO.ballhype.mediaAds<=3;hideShowFirstElement("media-player","div",true);hideShowFirstElement("post-data-ad","div",true);showPostMedia(a,b,c,d)}
function hideShowFirstElement(a,b,c){a=YAHOO.util.Dom.getElementsByClassName(a,b);if(a.length>0)c?YAHOO.util.Dom.addClass(a[0],"hidden"):YAHOO.util.Dom.removeClass(a[0],"hidden")}function unHideMediaPlayer(){hideShowFirstElement("media-player","div",false);hideShowFirstElement("post-data-ad","div",false);for(var a=YAHOO.util.Dom.getElementsByClassName("play-overlay","div"),b=0;b<a.length;b++)YAHOO.util.Dom.removeClass(a[b],"hidden")}
function showPortalPostMedia(a,b,c){var d=YAHOO.util.Dom.getXY("media."+a);d=[350,d[1]-200];_showPostMedia(a,b,c,false,d)}function showPostMedia(a,b,c,d){_showPostMedia(a,b,c,d,null)}
function _showPostMedia(a,b,c,d,e){YAHOO.ballhype.mediaPanel&&YAHOO.ballhype.mediaPanel.hide();for(var f=YAHOO.util.Dom.getElementsByClassName("play-overlay","div"),g=0;g<f.length;g++)YAHOO.util.Dom.addClass(f[g],"hidden");YAHOO.ballhype.mediaPanel=new YAHOO.widget.Panel("media."+a,{width:"525px",underlay:"shadow",close:true,visible:false,draggable:true,effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}});YAHOO.ballhype.mediaPanel.setHeader(b);a=new YAHOO.util.KeyListener(document,{keys:27},
{fn:YAHOO.ballhype.mediaPanel.hide,scope:YAHOO.ballhype.mediaPanel,correctScope:true});YAHOO.ballhype.mediaPanel.cfg.queueProperty("keylisteners",a);function h(){YAHOO.ballhype.mediaPanel.setBody("");unHideMediaPlayer()}YAHOO.ballhype.mediaPanel.hideEvent.subscribe(h);YAHOO.ballhype.mediaPanel.render();if(e==null){e=YAHOO.ballhype.mediaPanel.cfg.getProperty("y");e=[150,e]}YAHOO.ballhype.mediaPanel.moveTo(e[0],e[1]);YAHOO.ballhype.mediaPanel.show();e={success:function(i){i.argument[0].setBody(i.responseText);
i.argument[0].render()},failure:function(){},argument:[YAHOO.ballhype.mediaPanel]};c=YAHOO.ballhype.siUr+"video/"+c+"/media/";if(d)c+="?ads=true";YAHOO.util.Connect.asyncRequest("GET",c,e,null)}function isKHTML(){return navigator.userAgent.toLowerCase().indexOf("khtml")>-1}function navigateTo(a){document.location=a}function getVotingPath(){return YAHOO.ballhype.siNa=="BallHype"?"/media/img/hype/voting/":"/media/img/"+YAHOO.ballhype.siNa.toLowerCase()+"/voting/"}
function getVoteSelectedColor(){return YAHOO.ballhype.siNa.indexOf("Blips")>-1?"#ccc":"#fc0"}function getVoteColor(){return YAHOO.ballhype.siNa.indexOf("Blips")>-1?"#F2F1ED":"#FFC"}function getVoteTip(){return YAHOO.ballhype.siNa.indexOf("Hype")>-1?"hype it up!":"vote it up!"}YAHOO.ballhype.currBanner=0;function getCurrBannerElem(){return document.getElementById("banner."+YAHOO.ballhype.currBanner)}
function showBanner(){var a=getCurrBannerElem();YAHOO.util.Dom.setStyle(a,"opacity",0);YAHOO.util.Dom.removeClass(a,"hidden");a=new YAHOO.util.Anim(a,{opacity:{to:1}},0.6,YAHOO.util.Easing.easeOut);a.onComplete.subscribe(updateBannerLast);a.animate()}function hideBanner(){var a=getCurrBannerElem();YAHOO.util.Dom.addClass(a,"hidden")}
function updateBanner(){elem=getCurrBannerElem();var a=new YAHOO.util.Anim(elem,{opacity:{to:0}},0.6,YAHOO.util.Easing.easeOut);a.onComplete.subscribe(updateBannerNext);a.animate()}function updateBannerNext(){hideBanner();var a=0;storyCount=YAHOO.util.Dom.getElementsByClassName("banner-story","table","showhype-leaderboard").length;if(YAHOO.ballhype.currBanner+1<storyCount)a=YAHOO.ballhype.currBanner+1;YAHOO.ballhype.currBanner=a;showBanner()}
function updateBannerLast(){var a=setTimeout("updateBanner()",6000)}function pickQuizAnswer(a,b){if(YAHOO.ballhype.uli){a={success:function(c){var d=eval("("+c.responseText+")");handleQuizPickResponse(c.argument[0],d)},argument:[a]};b=YAHOO.util.Connect.asyncRequest("GET",b,a,null)}else showLoginOverlay(a,"ans.","answering quizzes")}
function handleQuizPickResponse(a,b){a=b.PickResults;for(var c in a.answers){answer=document.getElementById("answer."+c);if(b=document.getElementById("answer_picks."+c)){var d='<a href="javascript:showAnswerPicks('+c+", 'Picks');\">"+a.answers[c]+" pick";if(a.answers[c]!=="1")d+="s";d+="</a>";if(c==a.user_answer_id){d+=' <a href="javascript:pickQuizAnswer('+c+", '"+YAHOO.ballhype.siUr+"quiz/answer/clear/"+a.question_id+"/');\">[clear your pick]</a>";answer.className="selectedPick"}else answer.className=
"nonPick";b.innerHTML=d}}}
function showQuizAnswerMedia(a,b){YAHOO.ballhype.mediaPanel&&YAHOO.ballhype.mediaPanel.hide();YAHOO.ballhype.mediaPanel=new YAHOO.widget.Panel("media."+a,{width:"525px",underlay:"shadow",close:true,visible:false,draggable:true,effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}});YAHOO.ballhype.mediaPanel.setHeader(b);b=new YAHOO.util.KeyListener(document,{keys:27},{fn:YAHOO.ballhype.mediaPanel.hide,scope:YAHOO.ballhype.mediaPanel,correctScope:true});YAHOO.ballhype.mediaPanel.cfg.queueProperty("keylisteners",b);
function c(d,e){YAHOO.ballhype.mediaPanel.setBody("")}YAHOO.ballhype.mediaPanel.hideEvent.subscribe(c);YAHOO.ballhype.mediaPanel.render();b=YAHOO.ballhype.mediaPanel.cfg.getProperty("y");YAHOO.ballhype.mediaPanel.moveTo(150,b);YAHOO.ballhype.mediaPanel.show();b={success:function(d){d.argument[0].setBody(d.responseText);d.argument[0].render()},failure:function(d){},argument:[YAHOO.ballhype.mediaPanel]};a=YAHOO.util.Connect.asyncRequest("GET",YAHOO.ballhype.siUr+"quiz/answer/"+a+"/media/",b,null)}
function showQuizAnswersOverlay(a,b,c){if(YAHOO.ballhype.loginOverlays[a])YAHOO.ballhype.loginOverlays[a].show();else{var d=document.getElementById("overlay."+a);closeMessageOverlay(a);b=new YAHOO.widget.Panel(d,{context:[b+a,"tl","tl"],x:0,underlay:"shadow",visible:false,draggable:false,effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}});d=getRelativePath();b.setBody(c);c=new YAHOO.util.KeyListener(document,{keys:27},{fn:b.hide,scope:b,correctScope:true});b.cfg.queueProperty("keylisteners",
c);b.render();b.show();YAHOO.ballhype.loginOverlays[a]=b}}
function showAnswerPicks(a,b){YAHOO.ballhype.answerPickPanel&&YAHOO.ballhype.answerPickPanel.hide();YAHOO.ballhype.answerPickPanel=new YAHOO.widget.Panel("picks."+a,{width:"460px",underlay:"shadow",close:true,visible:false,draggable:true,effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}});YAHOO.ballhype.answerPickPanel.setHeader(b);b=new YAHOO.util.KeyListener(document,{keys:27},{fn:YAHOO.ballhype.answerPickPanel.hide,scope:YAHOO.ballhype.answerPickPanel,correctScope:true});YAHOO.ballhype.answerPickPanel.cfg.queueProperty("keylisteners",
b);function c(d,e){YAHOO.ballhype.answerPickPanel.setBody("")}YAHOO.ballhype.answerPickPanel.hideEvent.subscribe(c);YAHOO.ballhype.answerPickPanel.render();b=YAHOO.ballhype.answerPickPanel.cfg.getProperty("y");YAHOO.ballhype.answerPickPanel.moveTo(150,b);YAHOO.ballhype.answerPickPanel.show();b={success:function(d){d.argument[0].setBody(d.responseText);d.argument[0].render()},failure:function(d){},argument:[YAHOO.ballhype.answerPickPanel]};a=YAHOO.util.Connect.asyncRequest("GET",YAHOO.ballhype.siUr+
"quiz/answer."+a+"/picks/",b,null)}function showGamePicks(a,b,c){showGameDetails(a,"picks."+a+"."+b,"Picks - "+c,YAHOO.ballhype.siUr+"game."+a+"/picks/"+b+"/")}function showGameWatching(a,b){showGameDetails(a,"users."+a,"Users "+b,YAHOO.ballhype.siUr+"game."+a+"/users/")}
function showGameDetails(a,b,c,d){YAHOO.ballhype.gamePickPanel&&YAHOO.ballhype.gamePickPanel.hide();YAHOO.ballhype.gamePickPanel=new YAHOO.widget.Panel(b,{width:"460px",underlay:"shadow",close:true,visible:false,draggable:true,constraintoviewport:true,effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}});YAHOO.ballhype.gamePickPanel.setHeader(c);a=new YAHOO.util.KeyListener(document,{keys:27},{fn:YAHOO.ballhype.gamePickPanel.hide,scope:YAHOO.ballhype.gamePickPanel,correctScope:true});
YAHOO.ballhype.gamePickPanel.cfg.queueProperty("keylisteners",a);function e(f,g){YAHOO.ballhype.gamePickPanel.setBody("")}YAHOO.ballhype.gamePickPanel.hideEvent.subscribe(e);YAHOO.ballhype.gamePickPanel.render();a=YAHOO.ballhype.gamePickPanel.cfg.getProperty("y");YAHOO.ballhype.gamePickPanel.moveTo(150,a);YAHOO.ballhype.gamePickPanel.show();a={success:function(f){f.argument[0].setBody(f.responseText);f.argument[0].render()},failure:function(f){},argument:[YAHOO.ballhype.gamePickPanel]};d=YAHOO.util.Connect.asyncRequest("GET",
d,a,null)}
function showStoryVotes(a,b,c){YAHOO.ballhype.storyVotePanel&&YAHOO.ballhype.storyVotePanel.hide();YAHOO.ballhype.storyVotePanel=new YAHOO.widget.Panel(b,{width:"460px",underlay:"shadow",close:true,visible:false,draggable:true,constraintoviewport:true,effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}});YAHOO.ballhype.storyVotePanel.setHeader("Votes for "+c);b=new YAHOO.util.KeyListener(document,{keys:27},{fn:YAHOO.ballhype.storyVotePanel.hide,scope:YAHOO.ballhype.storyVotePanel,correctScope:true});
YAHOO.ballhype.storyVotePanel.cfg.queueProperty("keylisteners",b);function d(e,f){YAHOO.ballhype.storyVotePanel.setBody("");unHideMediaPlayer()}YAHOO.ballhype.storyVotePanel.hideEvent.subscribe(d);YAHOO.ballhype.storyVotePanel.render();b=YAHOO.util.Dom.getElementsByClassName("media-player","div");b.length>0&&YAHOO.util.Dom.addClass(b[0],"hidden");YAHOO.ballhype.storyVotePanel.show();b={success:function(e){e.argument[0].setBody(e.responseText);e.argument[0].render()},failure:function(e){},argument:[YAHOO.ballhype.storyVotePanel]};
a=YAHOO.util.Connect.asyncRequest("GET",YAHOO.ballhype.siUr+"story/"+a+"/votes/",b,null)}function snHover(){for(var a=YAHOO.util.Dom.getElementsByClassName("snnav","li","secondnav"),b=0;b<a.length;b++){a[b].onmouseover=function(){YAHOO.util.Dom.addClass(this,"snhover")};a[b].onmouseout=function(){YAHOO.util.Dom.removeClass(this,"snhover")}}}
function rnHover(){for(var a=YAHOO.util.Dom.getElementsByClassName("rnav","li","radar_nav"),b=0;b<a.length;b++){a[b].onmouseover=function(){YAHOO.util.Dom.addClass(this,"rnhover")};a[b].onmouseout=function(){YAHOO.util.Dom.removeClass(this,"rnhover")}}}if(window.attachEvent){window.attachEvent("onload",snHover);window.attachEvent("onload",rnHover)}
function swapLargeThumb(a){var b=document.getElementById("large-thumb");b.src=a.src;b.alt=a.alt;b.parentNode.href=a.parentNode.href;b.parentNode.title=a.parentNode.title}function swapBgr(a){document.body.style.backgroundImage=url(a);document.body.style.backgroundAttachment="fixed";document.body.style.backgroundPosition="top center";document.body.style.backgroundRepeat="no-repeat"}
function getCookie(a){var b=document.cookie.indexOf(a+"="),c=b+a.length+1;if(!b&&a!=document.cookie.substring(0,a.length))return null;if(b==-1)return null;a=document.cookie.indexOf(";",c);if(a==-1)a=document.cookie.length;return unescape(document.cookie.substring(c,a))}
function facebookLogin(a){if(YAHOO.ballhype.uli)return facebookLink(a);a||(a="");var b={success:function(c){a?navigateTo(a):reloadPage()},failure:function(c){facebookLinkForm(a)},argument:[]};b=YAHOO.util.Connect.asyncRequest("GET",YAHOO.ballhype.siUr+"external/facebook/login/",b)}
function facebookLink(a){var b={success:function(d){a?navigateTo(a):reloadPage()},failure:function(d){hideOverlay();alert("Sorry - this Facebook account has already been linked to a different account.")},argument:[]},c=YAHOO.ballhype.siUr+"external/facebook/link/";b=YAHOO.util.Connect.asyncRequest("GET",c,b)}
function facebookLinkForm(a){a||(a="");var b=FB.Connect.get_loggedInUser();function c(d,e){var f=d[0].name,g=d[0].pic_square_with_logo;e='<span class="header">Connect with Facebook</span>';d=d[0].proxied_email;d='<div id="fbc-link"><div class="fbc-title-wrapper"><div class="left"><img src="'+g+'"/></div><div class="fbc-title"><b>Welcome, '+f+'</b></div></div><div class="clearer"></div><div class="fbc-body-wrapper"><div id="fbc-new-mem" class="fbc-form left"><form onsubmit="return submitFacebookJoinForm(this);" action="'+
YAHOO.ballhype.siUr+'external/facebook/join/" method="POST"><p class="fbc-input-title">Username</p><p><input name="username" id="fbUsername" value="'+f+'" maxlength="30"/><div id="join-usernameError"></div></p><p class="fbc-input-title"><input type="checkbox" value="checked" checked name="use_profile_pic" class="checkbox"/>&nbsp;&nbsp;Use my Facebook photo as my pro\ufb01le photo</p><p class="fbc-submit"><input id="join-member-button" class="fsButton" type="submit" value="CREATE NEW ACCOUNT"/></p><p class="right-link"><a href="#" onClick="toggleFBCLinkForm();return false;">Already a  '+
YAHOO.ballhype.siNa+' member?</a></p><input type="hidden" name="profile_pic" value="'+g+'"/><input type="hidden" name="email" value="'+d+'"/><input type="hidden" name="facebook_user_id" value="'+b+'"/><input type="hidden" name="next" value="'+a+'"/></form></div><div id="fbc-old-mem" class="fbc-form left"><form onsubmit="return submitFacebookLinkForm(this);" action="'+YAHOO.ballhype.siUr+'external/facebook/link_login/" method="POST"><p>Log in to '+YAHOO.ballhype.siNa+' below, and we\'ll link your<br />Facebook account. You\'ll only have to do this once.</p><p class="fbc-input-title">Username</p><p><input name="username" maxlength="30"/><div id="link-usernameError"></div></p><p class="fbc-input-title">Password</p><p><input type="password" name="password"/></p><p class="fbc-submit"><input id="link-member-button" class="fsButton" type="submit" value="LINK MY ACCOUNTS"/></p><p class="right-link"><a href="#" onClick="toggleFBCLinkForm();return false;">Not a  '+
YAHOO.ballhype.siNa+' member?</a></p><input type="hidden" name="facebook_user_id" value="'+b+'"/><input type="hidden" name="next" value="'+a+'"/></div></div></form></div>';showOverlay("facebookOverlay",d,e);join_member_button=new YAHOO.widget.Button("join-member-button");link_member_button=new YAHOO.widget.Button("link-member-button");YAHOO.ballhype.sear||toggleFBCLinkForm()}FB.Facebook.apiClient.users_getInfo([b],["name","pic_square_with_logo","proxied_email"],c)}
function facebookJoinForm(a){a||(a="");var b=FB.Connect.get_loggedInUser();function c(d,e){e=d[0].name;var f=d[0].pic_square_with_logo;d=d[0].proxied_email;d='<div id="fbc-join"><form onsubmit="return submitFacebookJoinForm(this);" action="'+YAHOO.ballhype.siUr+'external/facebook/join/" method="POST"><div class="fbc-title-wrapper"><div class="left"><img src="'+f+'"/></div><div class="fbc-title"><b>Welcome, '+e+'</b></div></div><div class="clearer"></div><div class="fbc-body-wrapper"><div class="fbc-left"><p class="fbc-input-title">Choose a username </p></div><div class="fbc-right"><p><input name="username" id="fbUsername" value="'+
e+'" maxlength="30"/><div id="usernameError"></div></p><p class="fbc-input-title"><input type="checkbox" value="checked" checked name="use_profile_pic" class="checkbox"/>&nbsp;&nbsp;Use my Facebook photo as a pro\ufb01le photo</p><p class="fbc-submit"><input id="join-member-button" class="fsButton" type="submit" value="SUBMIT"/></p><p class="right"><a href="#" onClick="hideOverlay();return false;">Cancel</a></p><input type="hidden" name="profile_pic" value="'+f+'"/><input type="hidden" name="email" value="'+
d+'"/><input type="hidden" name="facebook_user_id" value="'+b+'"/><input type="hidden" name="next" value="'+a+'"/></div></div></form></div>';e="Connect with Facebook";showOverlay("facebookOverlay",d,e);join_member_button=new YAHOO.widget.Button("join-member-button")}FB.Facebook.apiClient.users_getInfo([b],["name","pic_square_with_logo","proxied_email"],c)}
function loadingOverlay(a,b,c){if(!YAHOO.ballhype.overlayPanel){a=document.getElementById(a);YAHOO.ballhype.overlayPanel=new YAHOO.widget.Panel(a,{underlay:"none",visible:false,draggable:false,modal:true,close:true,effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}})}b||(b="Loading, please wait");YAHOO.ballhype.overlayPanel.setBody('<div class="center">'+b+'<br /><img src="/media/img/loading.gif" width="32" height="32" alt="Loading" class="loading"></div>');c&&YAHOO.ballhype.overlayPanel.setHeader(c);
YAHOO.ballhype.overlayPanel.render();YAHOO.ballhype.overlayPanel.center();YAHOO.ballhype.overlayPanel.show()}
function showOverlay(a,b,c){if(!YAHOO.ballhype.overlayPanel){a=document.getElementById(a);YAHOO.ballhype.overlayPanel=new YAHOO.widget.Panel(a,{underlay:"none",visible:false,draggable:false,modal:true,close:true,effect:{effect:YAHOO.widget.ContainerEffect.FADE,duration:0.25}})}c&&YAHOO.ballhype.overlayPanel.setHeader(c);YAHOO.ballhype.overlayPanel.setBody(b);b=new YAHOO.util.KeyListener(document,{keys:27},{fn:YAHOO.ballhype.overlayPanel.hide,scope:YAHOO.ballhype.overlayPanel,correctScope:true});YAHOO.ballhype.overlayPanel.cfg.queueProperty("keylisteners",
b);YAHOO.ballhype.overlayPanel.render();YAHOO.ballhype.overlayPanel.center();YAHOO.ballhype.overlayPanel.show()}function hideOverlay(){YAHOO.ballhype.overlayPanel&&YAHOO.ballhype.overlayPanel.hide()}
function toggleFBCLinkForm(){var a=document.getElementById("fbc-new-mem"),b=document.getElementById("fbc-old-mem"),c=YAHOO.util.Dom.getStyle(b,"display");if(c=="none"){YAHOO.util.Dom.setStyle(a,"display","none");YAHOO.util.Dom.setStyle(b,"display","inline")}else{YAHOO.util.Dom.setStyle(b,"display","none");YAHOO.util.Dom.setStyle(a,"display","inline")}}function reloadPage(){location.reload()}function nonAscii(a){for(var b=0;b<a.length;b++)if(a.charCodeAt(b)>128)return true;return false}
function submitFacebookJoinForm(a){if(nonAscii(a.username.value)){alert("Please use only Latin characters or numbers in the username field.");return false}var b={success:function(d){d=eval("("+d.responseText+")");if(d.username){YAHOO.ballhype.overlayPanel.hide();var e=a.next.value.indexOf("http:")==0?a.next.value:escape(a.next.value);d=e?function(){navigateTo(e)}:function(){reloadPage()};FB.Connect.showPermissionDialog("email",d)}else if(d.errors){errorElem=document.getElementById("join-usernameError");
errorElem.innerHTML="That username is unavailable.  Please choose another.";YAHOO.util.Dom.addClass(errorElem,"error")}},failure:function(d){},argument:[]},c="username="+escape(a.username.value);c+="&email="+escape(a.email.value);c+="&facebook_user_id="+escape(a.facebook_user_id.value);if(a.use_profile_pic.checked)c+="&profile_pic="+escape(a.profile_pic.value);b=YAHOO.util.Connect.asyncRequest("POST",a.action,b,c);return false}
function submitFacebookLinkForm(a){var b={success:function(d){d=eval("("+d.responseText+")");if(d.username){YAHOO.ballhype.overlayPanel.hide();var e=a.next.value&&a.next.value.indexOf("http:")==0?a.next.value:escape(a.next.value);d=e?function(){navigateTo(e)}:function(){reloadPage()};FB.Connect.showPermissionDialog("email",d)}else if(d.errors){errorElem=document.getElementById("link-usernameError");errorElem.innerHTML="Invalid username/password.  Please try again.";YAHOO.util.Dom.addClass(errorElem,
"error")}},failure:function(d){},argument:[]},c="username="+escape(a.username.value);c+="&password="+escape(a.password.value);c+="&facebook_user_id="+escape(a.facebook_user_id.value);b=YAHOO.util.Connect.asyncRequest("POST",a.action,b,c);return false}function facebookConnectedUser(){return YAHOO.ballhype.fbCo&&YAHOO.ballhype.ufbc}
function showFacebookVoteFeed(a){var b=getFacebookAttachment(a);b.caption="{*actor*} voted for this story on "+YAHOO.ballhype.siNa+".";function c(d,e){d&&trackEvent("Share","Facebook","Vote Connect")}FB.ensureInit(function(){FB.Connect.streamPublish("",b,null,null,null,c)})}
function showFacebookCommentFeed(a){var b={success:function(c){c=eval("("+c.responseText+")");if(c.ShareComments){var d=getFacebookAttachment(c);d.caption="{*actor*} talked about this story on "+YAHOO.ballhype.siNa+".";function e(f,g){f&&trackEvent("Share","Facebook","Comment Connect")}FB.ensureInit(function(){FB.Connect.streamPublish("",d,null,null,null,e)})}},failure:function(c){},argument:[]};a=YAHOO.util.Connect.asyncRequest("GET",a,b)}
function showFacebookSubmitFeed(a){var b={success:function(c){c=eval("("+c.responseText+")");if(c.ShareSubmits){var d=getFacebookAttachment(c);d.caption="{*actor*} posted this story on "+YAHOO.ballhype.siNa+".";function e(f,g){f&&trackEvent("Share","Facebook","Submit Post Connect")}FB.ensureInit(function(){FB.Connect.streamPublish("",d,null,null,null,e)})}},failure:function(c){},argument:[]};a=YAHOO.util.Connect.asyncRequest("GET",a,b)}
function getFacebookAttachment(a){var b={name:a.Story.ShareTitle,href:a.Story.ShortPermalink,description:a.Story.Description+" \u2014"+a.Story.Server};if(a.Story.Thumbnail)b.media=[{type:"image",src:a.Story.Thumbnail,href:a.Story.ShortPermalink}];return b}function hideFacebookPrompt(a){hider_url=YAHOO.ballhype.siUr+"profile/"+a+"/hide_facebook_prompt/";YAHOO.util.Connect.asyncRequest("GET",hider_url)}
function doSidebarOffset(){var a=YAHOO.util.Dom.getXY("media-wrapper-end"),b=YAHOO.util.Dom.getXY("primary");if(a&&b){a=a[1]-b[1]+25;YAHOO.util.Dom.setStyle("sidebar","margin-top",a+"px")}}function toggleDisplayById(a,b,c){if(document.getElementById(b)){b=document.getElementById(b);YAHOO.util.Dom.getStyle(b,"display")!="none"?YAHOO.util.Dom.setStyle(b,"display","none"):YAHOO.util.Dom.setStyle(b,"display","block")}c&&YAHOO.util.Dom.setStyle(a,"display","none")}YAHOO.ballhype.carouselTooltips={};
function makeCarouselRequest(a,b,c,d){var e="?start="+c+"&numRes="+d;a={success:handleCarouselSuccess,failure:handleCarouselFailure,argument:[c,d,a]};b=b+e;YAHOO.util.Connect.asyncRequest("GET",b,a,null)}
function handleCarouselSuccess(a){var b=a.argument[0],c=a.argument[2],d=[];if(a.responseText!==undefined){a=eval("("+a.responseText+")");c.setProperty("size",a.totalPosts,true);for(var e=0;e<a.postList.length;e++){var f=a.postList[e],g=c.addItem(b+e,getCarouselVideosHtml(f));g.title=f.postTitle;d.push(g)}doSidebarOffset();if(d.length){var h="Video";function i(){trackEvent("Carousel",h)}YAHOO.util.Event.addListener(d,"click",i)}YAHOO.env.ua.webkit&&navigator.userAgent.indexOf("Chrome")>-1&&fixWebKitBrowserCarouselWidth("video-player-carousel");
showButtons()}}function handleCarouselFailure(){}function getCarouselVideosHtml(a){return a.postHtml}function loadInitialCarouselItems(a,b){a=b[0];b=b[1];b=(b-a+1)*4;makeCarouselRequest(this,YAHOO.ballhype.siUr+"story/"+YAHOO.ballhype.postId+"/top_videos_list/",a,b)}function loadMoreCarouselItems(a,b){a=b[0];var c=b[1];b=b[2];c=(c-a+1)*4;b||makeCarouselRequest(this,YAHOO.ballhype.siUr+"story/"+YAHOO.ballhype.postId+"/top_videos_list/",a,c)}
function handleCarouselButtonState(a,b){a=b[0];b=b[1];a?YAHOO.util.Dom.removeClass(b,"disabled"):YAHOO.util.Dom.addClass(b,"disabled")}function showButtons(){YAHOO.util.Dom.setStyle("vpc-next-arrow","visibility","visible");YAHOO.util.Dom.setStyle("vpc-prev-arrow","visibility","visible")}function fixWebKitBrowserCarouselWidth(a){YAHOO.util.Dom.setStyle(a,"width","550px")}function swfObjectStatus(a){a.success||alert("e.success = "+a.success+"\ne.id = "+a.id+"\ne.ref = "+a.ref)}
function playYumeContent(a,b){width="425";height="350";starting_volume=75;var c="/media/yume/swfs/yume_skin2.swf",d=Math.floor(Math.random()*100001);d="&rand="+d;a={auto_play:"true",yume_start_time:Number(1),yume_normalscreen_width:Number(width),yume_normalscreen_height:Number(height),yume_leader_slot:"false",yume_preroll_playlist:encodeURIComponent("http://pl.yumenetworks.com/dynamic_preroll_playlist.fmil?domain="+a+"&pubchannel="+b+"&imu=medrect"+d),yume_branding_playlist:"",yume_midroll_playlist:"",
yume_postroll_playlist:"",publisher_content_url:"",yume_swf_url:"/media/yume/swfs/yume_player_4x3.swf",yume_library_swf_url:"/media/yume/swfs/yume_swf_library.swf",my_skin:c,yume_set_volume:starting_volume};b={allowScriptAccess:"always",menu:"false",allowFullScreen:"true",scale:"noscale",wmode:"transparent"};c={id:"flash_flv_player"};swfobject.embedSWF("/media/yume/swfs/yume_publisherplayer.swf","flash_flv_player",width,height,"8",null,a,b,c)}
function yumeAdPlayer(a,b){var c=new yumeStaticCbAd;c.setPlayerMediumRectangleCompanionBannerDivSource("");c.setPlayerAdDomainUrl("http://pl.yumenetworks.com/");c.setPlayerIframeBannerPlaylist("dynamic_banner_iframe.html?domain="+a+"&pubchannel="+b)}YAHOO.ballhype.YouTubePlayerStates={unstarted:-1,ended:0,playing:1,paused:2,buffering:3,cued:5};YAHOO.ballhype.yume_play_count=0;YAHOO.ballhype.video_player_embed_html="";
function onYouTubePlayerStateChange(a){if(!YAHOO.ballhype.yume_play_count&&a==YAHOO.ballhype.YouTubePlayerStates.playing){ytplayer=document.getElementById("yt-player");if(ytplayer.getDuration()>YAHOO.ballhype.yume_minimum_length){ytplayer.pauseVideo();YAHOO.util.Dom.setStyle("wide-video-overlay","display","block");YAHOO.env.ua.ie>0?YAHOO.util.Dom.setStyle("yt-player","top","-5000px"):YAHOO.util.Dom.setStyle("yt-player","visibility","hidden");playYumeContent(YAHOO.ballhype.yume_domain,YAHOO.ballhype.yume_pubchannel)}YAHOO.ballhype.yume_play_count++}}
function onYumeFinish(){swfobject.removeSWF("flash_flv_player");YAHOO.util.Dom.setStyle("wide-video-overlay","display","none");YAHOO.env.ua.ie>0?YAHOO.util.Dom.setStyle("yt-player","top","0"):YAHOO.util.Dom.setStyle("yt-player","visibility","visible");ytplayer=document.getElementById("yt-player");ytplayer.seekTo(0);ytplayer.playVideo()}function onYouTubePlayerReady(a){ytplayer=document.getElementById("yt-player");ytplayer.addEventListener("onStateChange","onYouTubePlayerStateChange")}
function YouTubePlayerEmbedSWFCallback(a){if(!a.success){yt_embed=YAHOO.ballhype.video_player_embed_html;yt_embed=yt_embed.replace(/<\/?div[^>]*>/g,"");video_player=document.getElementById("wide-video-player");video_player.innerHTML=yt_embed}};
